# fly.toml app configuration file generated for berealapi on 2023-08-27T18:19:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "berealapi"
primary_region = "mad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
